steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/helloakash:$COMMIT_SHA", "--build-arg=JAR_FILE=target/hello-akash-1.0.0.jar", "."]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'helloakash'
    - '--image'
    - 'gcr.io/$PROJECT_ID/helloakash:$COMMIT_SHA'
    - '--region'
    - 'us-central1'  
images: ["gcr.io/$PROJECT_ID/helloakash:$COMMIT_SHA"]