steps:
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ["package", "-Dmaven.test.skip=true"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy ./target/poc-fs-api-0.0.1-SNAPSHOT.jar']
timeout: '1600s'